### ISSUE TITLE
The standard ingress configuration does not work

### ISSUE THREAD

**Issue by VA-PLE** [greenbone/openvas-scanner#1471]
Hi. I'm trying to deploy an official helmchart for openvas-scanner ``helm install openvasd ./openvasd/ -f openvasd/values.yaml``. I changed the ingress section as follows:

``` 
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: openvas-scanner.test.io
      paths:
        - path: /api/openvasd(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: openvasd
              port:
                number: 3000
  tls:
    - secretName: test.io
      hosts:
        - openvas-scanner.test.io
```

After the chart was deployed, I received the following message:
```
NOTES:
1. Get the application URL by running these commands:
  https://openvas-scanner.test.io/api/openvasd(/|$)(.*)
```

If I click on this link, I will see ```nginx 404 Not Found```
logs from nginx-ingress ``[16/Aug/2023:14:33:47 +0000] "GET /api/openvasd(/%7C$)(.*) HTTP/2.0" 404 548 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" 79 0.001 [upstream-default-backend] [] 127.0.0.1:8181 548 0.000 404 61ded5db88f4d1e0312d9d7ba0fa863d``

k8s v1.23.7
ingress-nginx/controller v1.3.1

Please tell me what could be the problem.
