### ISSUE TITLE
Nothing being served at "/" when deploying basic helm

### ISSUE THREAD

**Issue by jonathon2nd** [greenbone/openvas-scanner#1651]
### Expected behavior

I expect it to open.

### Actual behavior

404's but request made it to pod

### Steps to reproduce

Deploy openvasd, with very basic configs. Disable mTLS and token, as it will be protected by CloudFlare ZeroTrust

### GVM versions

v23.3.1 of helm chart
![image](https://github.com/greenbone/openvas-scanner/assets/52681917/578f3a8b-d5bd-475f-b7ac-d0548cf5dd2b)

### Environment

Kubernetes Version: v1.27.8

**Installation method / source:** (packages, source installation)

v23.3.1 of helm chart
![image](https://github.com/greenbone/openvas-scanner/assets/52681917/578f3a8b-d5bd-475f-b7ac-d0548cf5dd2b)

Values
```
routing:
  enabled: false
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
openvasd: 
  apikey: ""
  tls:
    certificates:
      deploy_server: false
      deploy_client: false
```

### Logfiles

```
2024-06-03T22:14:24.708307896Z 2024-06-03T22:14:24.708208Z TRACE from_path{path="/" mode=Service}: openvasd::controller::entry: Unknown path="/"
2024-06-03T22:14:24.708329369Z 2024-06-03T22:14:24.708235Z DEBUG openvasd::controller::entry
: process call method=GET path="/"
```
